name: Main workflow

on:
  pull_request:
  push:
  schedule:
    - cron: '5 14 * * *'

jobs:
  check-version-numbers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check version numbers
        run: ./version.sh
  
  package-python:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-latest
          - macos-13
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:      
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
           
      - name: Upload binary wheel
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./wheelhouse/*.whl
      
  deploy:
    environment:
      name: pypi
      url: https://test.pypi.org/p/libbash
    needs:
      - check-version-numbers
      - package-python
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test_pypi' || startsWith(github.ref, 'refs/tags')
    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: wheelhouse/

      - name: Deploy test distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
          skip_existing: true
